### ISSUE TITLE
Retrieving ps5bc json with additional info

### ISSUE THREAD

**Issue by pearlxcore** [andshrew/supreme-enigma#1]
After analyzing http requests from https://library.playstation.com/ I found a link that retrieve the ps5 backward compatibility but the json only return the compatibility status of the game but not other info like neoenable, region, category, psvr etc. How do you get those info? Or do you got it from different link? Or I need to add parameter/ variables to it?

This is example to get ps5bc of CUSA01363

`https://web.np.playstation.com/api/graphql/v1/op?operationName=backwardCompatibility&variables=%7B%22titleIds%22%3A%22CUSA01363%22%7D&extensions=%7B%22persistedQuery%22%3A%7B%22version%22%3A1%2C%22sha256Hash%22%3A%22*****03%22%7D%7D`

**Comment by andshrew** [comment]
Yes the API function only returns the backwards compatibility status for the title IDs which you submit to it, and no additional information about the title.

The other data is from the "tmdb" metadata json/xml files which the consoles access when you have a game installed. I've just combined the two datasets here for convenience. Have a look at http://kood.info/pstic/ and the readme for some more detail around how the URLs to these files are calculated (note the references in the credits).
